### ISSUE TITLE
Style attributes randomly reorder causing inconsistent styles

### ISSUE THREAD

**Issue by zachzurn** [jdrouet/mrml#154]
Styles take priority based on where they are in the css list. These properties are randomly ordered which causes style shifts when rendering the same mjml.

For example this set of style rules would end up adding a padding-top of 50px:

```css
padding: 0;
padding-top: 50px;
```

But with random ordering, this happens which makes the padding-top come out as 0:

```css
padding-top: 50px;
padding: 0;
```

Styles should remain in the same order in which they were defined, while also honoring the apply order that is mentioned in the mjml docs:

`Note that the apply order of attributes is: inline attributes, then classes, then default mj-attributes and then defaultMJMLDefinition`

- inline
- classes 
- mj-attributes
- default mjml styles

**Comment by jdrouet** [comment]
This comes from the use of a HashMap to store the styles when building the html. I will fix that this weekend.

**Comment by jdrouet** [comment]
@zachzurn could you try the version 1.3.1 of `mrml-cli`? It should to be fixed.

**Comment by zachzurn** [comment]
I’ll give it a run later today.

**Comment by zachzurn** [comment]
Ran an initial test and styles seem to be ordering properly with some minor exceptions. I'll be able to do some more testing next week with some real world templates I am working on.

Here are some notes when comparing the output between the two renderers. I am leaving out any whitespace formatting notes since they are irrelevant.

See attached zip here:
[output-mjml.zip](https://github.com/jdrouet/mrml/files/6488181/output-mjml.zip)

- Test input: styles-test.mjml
- MJML Output: mjml.html
- MRML Output: mrml.html

Notes:

Line 58 in the MRML output starts to differ. MRML seems to include the style tag even if it was specified as inline. There is also an erroneous second style tag with a media attribute.

MRML Output
```html
<style type="text/css">
    @media only screen and (min-width:480px) {
      .mj-column-per-100 {
        width: 100% !important;
        max-width: 100%;
      }
    }
</style>
<style media="screen and (min-width:480px)">
    .moz-text-html .mj-column-per-100 {
      width: 100% !important;
      max-width: 100%;
    }
</style>
<style type="text/css">
    .blue {
      color: #0000ff;
      text-decoration: underline;
      line-height: 30px;
    }
</style>
```

MJML Output

```html
<style type="text/css">
    @media only screen and (min-width:480px) {
      .mj-column-per-100 {
        width: 100% !important;
        max-width: 100%;
      }
    }
</style>
<style type="text/css">
</style>
```

MRML has a body style and a div with an empty style whereas MJML doesn't. I don't think the empty style tag breaks anything. but the word-spacing tag may have some unknown effects.

```html
<body style="word-spacing:normal;">
    <div style>
```

vs MJML

```html
<body>
    <div>
```

The style output looks the same with the exception of styles not being inlined.  I don't remember if inlining is currently supported in MRML yet, so this might be working exactly as expected.

One thing that might create unexpected results is the font-size:0px being later on in the definition for MJML (which might even break their own spec).

MRML Output
```html
<td align="right" class="blue" style="font-size:0px;padding:10px 25px;word-break:break-word;">
    <div style="font-family:helvetica;font-size:20px;line-height:1;text-align:right;text-decoration:none;color:#F45E43;">
        Hello World</div>
</td>
```

MJML Output
```html
<td align="right" class="blue" style="color: #0000ff; text-decoration: underline; line-height: 30px; font-size: 0px; padding: 10px 25px; word-break: break-word;">
    <div style="font-family:helvetica;font-size:20px;line-height:1;text-align:right;text-decoration:none;color:#F45E43;">
        Hello World</div>
</td>
```

**Comment by jdrouet** [comment]
> MRML has a body style and a div with an empty style whereas MJML doesn't. I don't think the empty style tag breaks anything. but the word-spacing tag may have some unknown effects.

If you use mjml 4.9.3 (I made a Docker image [here](https://hub.docker.com/r/jdrouet/mjml/tags?page=1&ordering=last_updated)) and the latest version of mjml seems to return the body with `word-spacing:normal;` so this might be due to the online editor not being up to date (I guess you're using it).

> There is also an erroneous second style tag with a media attribute.

Same thing, it seems valid according to the latest mjml version :thinking: 

> The style output looks the same with the exception of styles not being inlined. I don't remember if inlining is currently supported in MRML yet, so this might be working exactly as expected.

Nope, not yet supported. Why? Because the inline style requires to parse the generated html to apply the inline style afterward which will kill the performances and, IMO, using inline style should be avoided (although the generate html is already full of it). But it's on the roadmap.

Thank you for this feedback anyway, if you find a bug, don't hesitate to add the template in the PR and I'll try to fix the bug as soon as I can :wink:

**Comment by jdrouet** [comment]
I close this issue for now, don't hesitate to re-open one if you find anything wrong.
