### ISSUE TITLE
Support for lang attribute in mjml tag

### ISSUE THREAD

**Issue by zachzurn** [jdrouet/mrml#203]
👋

When adding the `lang` attribute to the `<mjml>` tag, mrml-cli sees it as an error.

MJML currently supports this attribute and adds the lang attribute into the html tag.

`<mjml lang="en-US">`

becomes

`<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">`

References:
Github commit: https://github.com/mjmlio/mjml/pull/1167/commits/c700c56d39e860b4d05d65b40184dc96fb990ac7

Docs: https://documentation.mjml.io/#mjml

**Comment by jdrouet** [comment]
👋 if you're using the `mjml` library, try using `1.2.5` version I just released 😉

**Comment by zachzurn** [comment]
I'll give it a go and report back 👍

**Comment by zachzurn** [comment]
Tested and working. Thanks!!
