### ISSUE TITLE
Support for mj-raw in mj-head

### ISSUE THREAD

**Issue by zachzurn** [jdrouet/mrml#204]
Using `mj-raw` in `mj-head` breaks the mrml-cli compiler. 

The documentation for this is in a weird place on the mjml docs under 'Standard Body Components' but the `<mj-raw>` tag can actually be used within `<mj-body>` and `<mj-head>` components.

From the docs:
> Displays raw HTML that is not going to be parsed by the MJML engine. Anything left inside this tag should be raw, responsive HTML. If placed inside `<mj-head>`, its content will be added at the end of the `<head>`.

Refs:
https://documentation.mjml.io/#mj-raw

**Comment by zachzurn** [comment]
Tested and it looks to be working properly.

**Comment by jdrouet** [comment]
👍 thank you for reporting the issue 😉
