### ISSUE TITLE
Support parsing elements with no closing tag 

### ISSUE THREAD

**Issue by DGulshan** [jdrouet/mrml#221]
I am trying to parse MJML that includes `<br>` tags, but I get the following error: `invalid format`. JavaScript parser for MJML doesn't seem to have to this issue. For example, the following MJML renders without any issues on https://mjml.io/try-it-live:

```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text><br>Some Test Content</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

It works when I replace `<br>` with `<br/>` but I am trying to parse some external templates and in some of these templates, `<br>` tags have additional data attributes, so I can't do a simple find and replace.

Please let me know if this can be supported.

**Comment by nguyenquannnn** [comment]
Bump, Imo i think there's valid need for these. If @jdrouet can propose a direction, maybe migrating to a different parser can be work on :)

**Comment by paulgoetze** [comment]
@jdrouet would (some?) other void elements also needed to be ignored similar to `br` and `meta`? E.g. `<hr>` comes to mind, which might be used one or the other time.

https://html.spec.whatwg.org/multipage/syntax.html#void-elements

**Comment by jdrouet** [comment]
@paulgoetze thanks for finding this! I'll update it!

**Comment by jdrouet** [comment]
@paulgoetze done and released ;)

**Comment by marcelolx** [comment]
@jdrouet could we support the same for the `mj-raw` element? It looks like support for self closing elements was just added to the `mj-wrapper`?

**Comment by jdrouet** [comment]
Hey,
Let me take a look when I have some time.
Could you open a new issue with an example?
Thanks
