### ISSUE TITLE
Panic rendering HTML inside Ending Tag

### ISSUE THREAD

**Issue by MateusAquino** [jdrouet/mrml#253]
Hey, thank you so much for creating this amazing cli :)

I was testing some code and found out that using HTML inside `mj-social-element` panicked the mrml-cli compiler.

Sample:

```mjml
<mjml>
  <mj-body>
    <mj-section background-color="#e7e7e7">
      <mj-column>
        <mj-social>
          <mj-social-element name="facebook">
            Share <b>test</b> hi
          </mj-social-element>
        </mj-social>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

Output:

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "unable to parse mjml: UnexpectedElement(166)"', /home/mafios/.cargo/registry/src/github.com-1ecc6299db9ec823/mrml-cli-1.3.2/src/main.rs:52:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

From the docs the inner content should be rendered just like `mj-raw`/`mj-text`:

> Some of the mjml components are "ending tags". These are mostly the components that will contain text contents, like mj-text or mj-buttons. These components can contain not only text, but also any HTML content
> 
> Here is the list of all ending tags : - mj-accordion-text - mj-accordion-title - mj-button - mj-navbar-link - mj-raw - mj-social-element - mj-text - mj-table

Refs:
https://documentation.mjml.io/#ending-tags

**Comment by jdrouet** [comment]
@MateusAquino thanks for the report, I'll take care of it 😉
