### ISSUE TITLE
mjml "owa" attribute is causing panic UnexpectedAttribute(16) 

### ISSUE THREAD

**Issue by nguyenquannnn** [jdrouet/mrml#266]
I was running into this error message `Failed to parse template: UnexpectedAttribute(16)` after adding `owa="desktop"` into the MJML template like this: `<mjml lang="en" owa="desktop">`. From this recent [PR](https://github.com/mjmlio/mjml/pull/2245), the attribute should be supported as an optional attribute. Is it possible to support this feature?

Environment: macOS 11.5.2 (20G95) 
Version: mrml v1.2.7

When I run this template on the live sandbox, I'm not facing any error

**Comment by jdrouet** [comment]
Thanks for this, I'll try to fix it shortly 😉
