### ISSUE TITLE
Any plans to release the CLI as compiled binaries?

### ISSUE THREAD

**Issue by brunoarueira** [jdrouet/mrml#283]
Hello, great work here!

Are there any plans to offer releases of the CLI as compiled binaries? Like other OSS projects with binaries for x86_64, musl and others?

Thanks,

**Comment by brunoarueira** [comment]
@jdrouet My requirements is to download the CLI on a container based on alpine and/or debian, to use with ruby applications for now since it's more faster than the oficial one.

Thanks in advance,

**Comment by purung** [comment]
Just to chime in on this, here's what you get if you try to add mrml-cli with `cargo binstall mrml-cli`:

```
INFO resolve: Resolving package: 'mrml-cli'
WARN Package does not specify repository, cargo-binstall cannot provide default pkg_url for it.
WARN The package mrml-cli v1.4.3 will be installed from source (with cargo)
Do you wish to continue? yes/[no]
```

Which I guess is not that bad, but it seems an easy fix since binaries are now distributed via github.

**Comment by jdrouet** [comment]
👋 Hey @purung , thanks for this!
I'll try to fix that when I'll have time.
Feel free to open a PR 😉

**Comment by jdrouet** [comment]
After almost 2y, I'm happy to close this: https://github.com/jdrouet/mrml/releases/tag/mrml-cli-v1.4.6

**Comment by brunoarueira** [comment]
Congrats @jdrouet , better late than never!

I'll test this asap.

ty :heart:
