### ISSUE TITLE
mrml produces incorrect output

### ISSUE THREAD

**Issue by actualwitch** [jdrouet/mrml#300]
It seems having an `mj-column` with `inner-background-color` breaks bg color on every element inside it:
```
<mjml>
<mj-body>
  <mj-section>
    <mj-column padding="1px" background-color="#E7E7E7" inner-background-color="#fff" border-radius="6px" inner-border-radius="6px">
      <mj-text>
        Hello World!
      </mj-text>
    </mj-column>
  </mj-section>
</mj-body>
</mjml>
```
Renders correctly on mjml, but is wrong in mrml:
<img width="726" alt="Screenshot 2023-01-10 at 16 41 31" src="https://user-images.githubusercontent.com/90313638/211597065-0a9583e2-8d04-41b1-a2ca-62074e57637a.png">

**Comment by jdrouet** [comment]
Hey!
Could you give me the version of MJML you're using and the version od MRML you're using?

**Comment by actualwitch** [comment]
I'm using mjml 4.13.0 as npm module on node 19.4 and mrml 1.2.10 (also as module) on rust 1.66

**Comment by actualwitch** [comment]
thanks for a quick fix!

**Comment by jdrouet** [comment]
releasing right now 😉

**Comment by jdrouet** [comment]
done: https://crates.io/crates/mrml
