### ISSUE TITLE
bug: border rendered twice when padding present

### ISSUE THREAD

**Issue by dawidl022** [jdrouet/mrml#466]
Given this simple snippet of MJML, with a border and a padding on an `mj-column`:

```mjml
<mjml>
  <mj-body>
    <mj-section>
      <mj-column padding-left="10px" border="3px solid black">
        <mj-text>Hello World</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

The expected outcome is as follows ([view in MJML live editor](https://mjml.io/try-it-live/gnF8GPlMx_)):

![image](https://github.com/user-attachments/assets/f58aeff9-e39c-4eea-bf22-1d51d6a59f8e)

However, mrml renders two borders: one outside of the column's padding, and one on the inside:

![image](https://github.com/user-attachments/assets/4be5ff8e-9370-484a-84f7-f30fd652b56e)

I believe this is a bug. When no padding is present on the column, a single border is correctly rendered.

The code used to render the MJML uses the default rendering options:

```rust
mrml::parse(mjml)?.render(&Default::default())?
```

**Comment by jdrouet** [comment]
Fixed by https://github.com/jdrouet/mrml/pull/479
