### ISSUE TITLE
Allow Sendgrid unsubscribe tags

### ISSUE THREAD

**Issue by simoheinonen** [jdrouet/mrml#470]
```mjml
<mjml>
    <mj-body>
        <a href="<%asm_group_unsubscribe_raw_url%>">unsubscribe</a>
    </mj-body>
</mjml>
```

`couldn't parse document: something went wront while parsing invalid attribute at 3:11 cause expected '"' not '<' at 3:18`

https://www.twilio.com/docs/sendgrid/ui/sending-email/group-unsubscribes

**Comment by jdrouet** [comment]
So this issue comes from `xmlparser` which we use under the hood to parse the template.
That being said, this is a real problem and what you ask should be possible.
I'm on it.
