### ISSUE TITLE
Support mj-include tag

### ISSUE THREAD

**Issue by nacardin** [jdrouet/mrml#61]
I would like to be able to reuse template fragments. What do you think about supporting taking in a map of <path, content>, so that mrml wouldn't have to search for the includes at runtime?

**Comment by jdrouet** [comment]
Thanks @nacardin for your interest.
Regarding your request, this brings a complex things to solve: mrml is supposed to work as a cli, but also in the browser (wasm) so the mj-include should be handled there as well.
I'll take a look at this important feature soon and probably integrate it with jolimail.

**Comment by petejodo** [comment]
so just to make sure I understand, you want to be able to support the following?

```html
<mj-include path="./partial.html" type="html"/>
<mj-include path="file://localhost/path/to/partial.html" type="html"/>
<mj-include path="https://example.com/path/to/partial.html" type="html"/>
```

how do you expect to handle loading files since wasm doesn't support file IO out of curiosity?

**Comment by drush** [comment]
Could the first pass at this feature work on the CLI only?  WASM support and remote URLs is interesting, but likely a really bad idea from a security standpoint.  I think the CLI/includes case is an 80% solution.

**Comment by jdrouet** [comment]
that's a good idea. I've to update the library with the latest mjml updates and will work on this 😉

**Comment by jdrouet** [comment]
`mj-include` is now supported
