### ISSUE TITLE
Use other repository of social icons

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [jdrouet/mrml#83]
Is it an official requirement to use this url: https://github.com/jdrouet/mrml/blob/main/packages/library/src/elements/body/mj_social/element.rs#L12

I use Sendgrid and it seems it bloc me this URL.
Can we use a specific configuration to use an another base URL and keep it by default that one ?

**Comment by jdrouet** [comment]
@MarcAntoine-Arnaud update to release 0.4.0, you should be able to pass it to the parser.
https://github.com/jdrouet/mrml/blob/main/packages/library/src/lib.rs#L29
